### ISSUE TITLE
Link mirror and record buttons on menu to buttons on controllers

### ISSUE THREAD

**Issue by courtneymcbeth** [parasollab/VR_Robot#16]
For ease of use, we'd like to be able to press a button on the handheld controller to stop mirroring the configuration of the robot and to start, reset, or send a recording (these can be different buttons). There are some buttons on the menu that toggle their functions/text when they are pressed and we should make sure the many buttons are still updated when the handheld controller buttons are used instead of the menu buttons themselves.

**Comment by fernandofks** [comment]
I did two pull requests, for [RADER](https://github.com/parasollab/RADER/pull/7) and for [VR_ROBOT](https://github.com/parasollab/VR_Robot/pull/25).
